# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribes', models.CommaSeparatedIntegerField(max_length=200)),
                ('friends', models.CommaSeparatedIntegerField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('expire', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo1.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('equip', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo1.Color')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('photoUrl', models.CharField(max_length=500)),
                ('auth_status', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo1.Role')),
                ('skills', models.ManyToManyField(to='Demo1.Skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo1.User'),
        ),
    ]
