# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo1', '0002_auto_20160121_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.CommaSeparatedIntegerField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscribes',
            field=models.CommaSeparatedIntegerField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='color',
            name='g',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='color',
            name='r',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='equip',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='photoUrl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
