# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo1', '0004_auto_20160121_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
