# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo1', '0005_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(to='Demo1.Skill'),
        ),
    ]
